<script setup lang="ts">
const accepted = ref(false)
const emit = defineEmits<{
  continue: []
}>()
</script>

<template>
  <section class="phone" aria-labelledby="consent-title">
    <p id="consent-title" class="consent-copy">
      Your Wellness Score is generated by Shen.AI OU, our third-party scanning partner, using a quick face scan.
      Your data is processed and stored on your device only - never on our servers.
    </p>

    <label class="consent-check">
      <input v-model="accepted" type="checkbox" />
      <span>
        I have read and accept the
        <a href="#" @click.prevent>Terms of Use</a>
        and
        <a href="#" @click.prevent>Consent</a>.
      </span>
    </label>

    <button class="consent-button" :disabled="!accepted" @click="emit('continue')">
      Continue
    </button>
  </section>
</template>

<style scoped>
.phone {
  padding: 18px;
  background: #fff;
  color: #222;
  font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
}

.consent-copy {
  margin: 0 0 18px;
  font-size: 15px;
  line-height: 1.42;
}

.consent-check {
  display: grid;
  grid-template-columns: 20px 1fr;
  gap: 10px;
  align-items: start;
  margin-bottom: 18px;
  font-size: 13px;
  line-height: 1.35;
}

.consent-check input {
  width: 20px;
  height: 20px;
  margin: 0;
  accent-color: #111;
}

.consent-check a {
  color: #111;
  font-weight: 600;
  text-decoration: underline;
}

.consent-button {
  appearance: none;
  border: 0;
  border-radius: 999px;
  padding: 10px 20px;
  min-width: 98px;
  background: #111;
  color: #fff;
  font: inherit;
  font-size: 14px;
  font-weight: 700;
  cursor: pointer;
}

.consent-button:disabled {
  background: #9aa3aa;
  cursor: default;
}
</style>